#Задача: xor

#Given 2 strings, return a string generated by XORing them. Of course, you XOR their bit representations.

#Example: "5*" == solution("xor", "ME")

#https://github.com/h/b/blob/master/src/b/issues/xor.clj

# BEGIN implement function `solution` here 
def solution(a, b)
  a.chars.zip(b.chars).map do |i, j|
    if i && j
      (i.ord ^ j.ord).chr
    end
  end.compact.join
end
# END

